### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by giacomoorsi** [giacomoorsi/OpenRitardi#1]
This PR will track the future updates of the project. 

# Italy 🇮🇹
Goal: obtain media coverage and get an impact
## Technical milestones to be achieved: 
- [ ] Italian translation #16 
- [ ] Improve data science #27 

## Data science improvement
The website needs to tell a story, which is not the case right now. 
Some ideas: 
- [ ] #27
- [ ] Update data: #25
- [ ] identify trains which run delayed on all stops apart from the last one
- [ ] identify trains which are structurally always late
- [ ] show worst trains by the percentage of times that they're late, rather than avg minutes

# General upgrades
- [ ] Add legend for dot size in homepage
- [ ] Add link to GitHub and contributors panel
- [ ] Improve community 
- [x] Support multiple translations #10 
- [x] Mobile Version #11 . Thanks @AndreaLaGrotteria !

**Comment by hadriensevel** [comment]
**Javascript**
- [ ] Refactoring of the javascript code (#3, #5)
- [ ] Use of a bundler like [Rollup](https://rollupjs.org) to optimize, organize and avoid redundant code (#6)
